cache:
    directories:
        - opencv-3.4.1

addons:
    apt:
        packages:
            - build-essential
            - cmake
            - git
            - libgtk2.0-dev
            - pkg-config
            - libavcodec-dev
            - libavformat-dev
            - libswscale-dev
            - libtbb2
            - libtbb-dev
            - libjpeg-dev
            - libpng-dev
            - libtiff-dev
            - libjasper-dev
            - libdc1394-22-dev
            - python-dev
            - python-numpy
            - libboost-all-dev
            - librtmidi-dev
            - libsdl2-dev

language:
  - cpp

compiler:
  - gcc
  
before_install:
  # Get or update the opencv repo
  - git clone https://github.com/opencv/opencv.git || (cd opencv ; git pull; cd ..)
  - cd opencv

  # Create a new 'build' folder.
  - mkdir -p build
  - cd build

  # Get or update the contrib modules
  - git clone https://github.com/opencv/opencv_contrib.git || (cd opencv_contrib ; git pull; cd ..)
  
  # Build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -D WITH_TBB=ON -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -DBUILD_DOCS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules -D BUILD_opencv_freetype=OFF -D ENABLE_PRECOMPILED_HEADERS=OFF ..
  
  # Run 'make' with four threads.
  - make -j4
  
  # Install to OS.
  - sudo make install
  
  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  
  - sudo ldconfig
  - echo "OpenCV installed."
  
  # We need to return to the repo "root" folder, so we can then 'cd' into the C++ project folder.
  - cd ../../
  # Update timestamps so autotools doesn't require rebuilding
  - touch *
